### ISSUE TITLE
Bot not reacting to servers with channel categories

### ISSUE THREAD

**Issue by godtotoro** [ScarletKuro/NadekoBot#11]
it just doesn't respond.

**Comment by Macleykun** [comment]
The newer version of Nadeko fixed this issue.
There are only three options for you to solve this.
1. You have to remove the categories of all the servers.
2. You have to host the latest nadeko by yourself.
3. Kuro decides it's worth re-coding the project to solve this issue.

If i were you just go for option 1.

**Comment by Macleykun** [comment]
You can close this btw, it's known :P

**Comment by ScarletKuro** [comment]
Updated the bot and the guide
