### ISSUE TITLE
repo for https://github.com/Kwoth/Discord.Net/ not found﻿

### ISSUE THREAD

**Issue by edvardavd** [ScarletKuro/NadekoBot#13]
Hello, ScarletKuro!

```
$ git clone -b master --recursive --depth 1 --progress https://github.com/ScarletKuro/NadekoBot.git
Cloning into 'NadekoBot'...
remote: Counting objects: 506, done.
remote: Compressing objects: 100% (420/420), done.
remote: Total 506 (delta 127), reused 268 (delta 76), pack-reused 0
Receiving objects: 100% (506/506), 3.84 MiB | 729.00 KiB/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done.
Submodule 'Discord.Net' (https://github.com/Kwoth/Discord.Net) registered for path 'Discord.Net'
Cloning into 'Discord.Net'...
remote: Repository not found.
fatal: repository 'https://github.com/Kwoth/Discord.Net/' not found
fatal: clone of 'https://github.com/Kwoth/Discord.Net' into submodule path 'Discord.Net' failed
```

Do you know how to fix it? (

**Comment by Macleykun** [comment]
You want to host a newer version of the bot correct?

**Comment by edvardavd** [comment]
@Macley-Kun Yes. Newest version.

**Comment by Macleykun** [comment]
Kuro probably will tell you that he doesn't want to update it, due to the amount of work that has to be done.

I would recommand using my previous suggestion or hosting a 1.3b version.

**Comment by edvardavd** [comment]
@Macley-Kun Which solution is the easiest? :smiley_cat:

**Comment by Macleykun** [comment]
Use kuro's 1.3b version. If you have it working, it'll stay working for a very long time :-)
the skysilk solution isn't gonna last long.

Make sure to follow Kuro's steps carefully, and read them entirely before beginning!

**Comment by ScarletKuro** [comment]
This repository is outdated, I'm not working on this anymore so this method is kinda dead.

**Comment by Macleykun** [comment]
Mhm to all good comes and end :-)
Maybe put that on the readme for new/existing users?

@edvardavd you can close your issue btw.

**Comment by edvardavd** [comment]
@ScarletKuro Очень жаль (

**Comment by ScarletKuro** [comment]
@edvardavd I have updated the guide and the bot.
