### ISSUE TITLE
Dyno not detect app

### ISSUE THREAD

**Issue by R00tS3c** [ScarletKuro/NadekoBot#21]
This app has no process types yet

**Comment by Macleykun** [comment]
What exactly do you mean?
You need to use the one from the release page. It has a procfile with a worker type defined in it.

**Comment by ScarletKuro** [comment]
Can you explain it more clear what problem do you have?

**Comment by ScarletKuro** [comment]
You can try to use one click heroku deployment that i have created.
https://dashboard.heroku.com/new-app?template=https://github.com/ScarletKuro/NadekoBot-Heroku-Auto-Deploy
All you need is to add client id, token id and owner id
