### ISSUE TITLE
.give

### ISSUE THREAD

**Issue by R00tS3c** [ScarletKuro/NadekoBot#22]
Command take flower from first user but not give other user.

**Comment by ScarletKuro** [comment]
You sure? I have tested with mssql and pgsql and it was fine for me
![screen](https://user-images.githubusercontent.com/19953225/48407162-defe5a80-e73e-11e8-9f75-afcecaa1f449.png)

**Comment by R00tS3c** [comment]
pgsql 
![image](https://user-images.githubusercontent.com/19959840/48435855-b184d180-e77d-11e8-9101-360dc5cbd874.png)

**Comment by R00tS3c** [comment]
no error in console

**Comment by ScarletKuro** [comment]
Indeed, found the problem and fixed [24ceeca](https://github.com/ScarletKuro/NadekoBot/commit/24ceecac58b8033125f1a5af80c094c786e2bafb#diff-8c39e7a69b32abae5870755281b7dbc8R185)
Working fine now
Thanks, closing it now.
