### ISSUE TITLE
source?

### ISSUE THREAD

**Issue by Lumilyu** [ScarletKuro/NadekoBot#26]
hey there, is there any way to edit the source files from the bot ?

**Comment by ScarletKuro** [comment]
Yeah, all the code is open. If you want to edit the code, you can fork/download this repository. Once you made your changes in code, you can do dotnet publish command, and then upload the compiled files to heroku or any other hosting.

**Comment by Lumilyu** [comment]
how would I do that exactly ? I'm kind of a beginner on all that, and all I've been able to understand as of right now is how to push the "1.9 release" files I downloaded, but that's not it right ? "How do I actually push my forked repository on the bot/heroku" is what I don't know how to do/understand ?

**Comment by Macleykun** [comment]
You probably refer to having a fork of Kuro's repo.
And making changes in your fork.
And that each commit will be pushed to Heroku.

You do this by doing the following:
![image](https://user-images.githubusercontent.com/26381427/53406002-576cec80-39b9-11e9-9eae-4f12e72fddeb.png)
Simpley click that you want to connect your github to your heroku app, choose right fork.
and if you scroll down, you can set auto deploy on, think that's what your after.

Btw don't forget to add the env variables yourself! Otherwise you have to add those sensitive credentials in your fork what you don't want :P

**Comment by ScarletKuro** [comment]
There is whole guide section on [heroku](https://devcenter.heroku.com/articles/git#deploying-codel).
And if you open your bot on heroku dashboard, there is "deploy" section, and it will show you 3 methods how to push your changes, the most easiest is to use github, then heroku cli.

**Comment by Lumilyu** [comment]
@Macley-Kun 
what do you mean by "env variables" ?

**Comment by Macleykun** [comment]
The variabeles that are set by using the template, or that are manual added to the heroku app to insert information like tokens.

**Comment by Lumilyu** [comment]
@Macley-Kun mhm, I tried simply manually adding the token and all to the credential.json on my fork, then tried pushing the repository to heroku, but logs give me a 
```BotCredentials | Token is missing from credentials.json or Environment varibles. Add it and restart the program. (not retained)```
did I do something wrong then ? 
The repository to push to heroku is the autodeploy one right ? Did I miss another step after deploying it ?

**Comment by Macleykun** [comment]
***********************************
***  RESET YOUR BOT TOKEN  ***
***********************************

Hey loki, you don't have to ping me each time, no need for that.
Second, i told you that this isn't a good practise:
https://github.com/Loki940/NadekoBot/commit/990a0838f2a4a785a5c2ab4524d76a64add74d33
Now everyone can use your token and use your bot to access your server (like deleing all channels for example)

i think you can beter do the following so things go beter.
delete your fork.
use Kuro's extremely easy to use and easy to fill in heroku button (it's on his READ.ME can't miss it)
try just getting the bot to work in heroku then. If that works THEN you can do the following

fork kuro's repo, then you can add that fork like so:
![image](https://user-images.githubusercontent.com/26381427/53420854-db849b80-39dc-11e9-94d5-98b2cbda96fe.png)

Then, you will get the information from that fork of yours, and your env variables are all set.

***********************************
***  RESET YOUR BOT TOKEN  ***
***********************************

**Comment by Lumilyu** [comment]
Ah sorry, I'm not used to github and since it was on Scarlet's repository, I wasn't sure you'd properly get the notification even without the ping, alright, I resetted the token, I'll try what you said when I have time, thanks for your help

**Comment by Macleykun** [comment]
Believe this was solved in Pm. Can be closed.
