### ISSUE TITLE
Dyno isnt showing up

### ISSUE THREAD

**Issue by BlazeDraaws** [ScarletKuro/NadekoBot#27]
i deployed it with "git push heroku HEAD:master" since it popped up this error when i tried it normally "error: src refspec master does not match any."
dyno shows up as
"This app has no process types yet
Add a Procfile to your app in order to define its process types. Learn more"
i downloaded your nadekobot but replaced "Data" folder with my original to keep the nadekobot.db and images.json

**Comment by BlazeDraaws** [comment]
is there a way to add nadekobot.db and images.json **and** use the one button method?

**Comment by Macleykun** [comment]
No you don't want to use nadekobot.db with heroku.
Why? As explained in the README all changes done within the application are lost when it's stopped. Normally you would use a remote database, the changes you make are then kept safe.

Images.json can maybe be done with the button, but i suggest that you do this then.
go to the deploybutton version of kuro's bot, FORK and then change the image.json, you can then click on the button ON YOUR FORK (and please check that you are indeed deploying from your fork!)

You probably are using something else in your first message, Kuro has the Procfiles everywhere correctly inplace.

**Comment by ScarletKuro** [comment]
Hello. 
nadekobot.db is part of the sqlite, which we don't use in the heroku, so no you can't use that.
And yes, you can have custom images.json, you have to fork the https://github.com/ScarletKuro/NadekoBot-Heroku-Auto-Deploy then you have to edit the image.json and upload the changes on your repository after that you need to go this url https://dashboard.heroku.com/new-app?template=your_github_url_to_the_repository_that_you_have_forked.

**Comment by BlazeDraaws** [comment]
ah okay thanks for the information
