### ISSUE TITLE
Making modifications to the auto deployed version.

### ISSUE THREAD

**Issue by jtbry** [ScarletKuro/NadekoBot#28]
Does the Heroku auto-deploy version of this project differ from this source? I have made modifications (At first to the original NadekoBot but then to this one) which run fine on my local machine but when I go to put it on Heroku all sorts of errors have been happening.

At first it was just issues with getting it running, got that working and then it was config errors (config vars not prefixed with NadekoBot)

It is now giving me path issues (`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/data/images.json'`) but when I revert to a pure version of the auto-deploy, it all works.

When deploying I:
Build this project in release mode on MSVC 2019
Move the newly made NadekoBot.Core.dll and NadekoBot.Core.pdb to the heroku repo
Push to heroku

Any ideas as to what's going wrong here would be great!

**Comment by jtbry** [comment]
Side note: when trying to run the bot from the Heroku based git repo it gets stuck on
`-1 16:06:36 ShardsCoordinator | Starting shard 0, 0 more in queue.` and doesn't load.

But when I run `dotnet run .\bin\Release\netcoreapp2.1\NadekoBot.dll ` in the MSVC project folder it runs fine.

**Comment by ScarletKuro** [comment]
> Does the Heroku auto-deploy version of this project differ from this source?

No. The auto-deploy is build from this repository.

> I have made modifications 

Sorry, I'm not giving advices when someone is doing modifications. I don't even know what have you modified, how you compiling, and deploying it. 

Can only recommend to run the stock auto deploy nadeko, since it tested by the time.

**Comment by jtbry** [comment]
> Sorry, I'm not giving advices when someone is doing modifications. I don't even know what have you modified, how you compiling, and deploying it.

Well I've only added a service and a command group to instantiate the service. As well as a field to the bot config. Nothing essential to the running of the bot. All changes, I would think, have no different to the bot being deployed any way differently than normal. 

My changes run fine locally but it all goes to whack on Heroku and due to the nature of Heroku it's hard to figure out exactly why.

**Comment by ScarletKuro** [comment]
> 
> 
> > Sorry, I'm not giving advices when someone is doing modifications. I don't even know what have you modified, how you compiling, and deploying it.
> 
> Well I've only added a service and a command group to instantiate the service. As well as a field to the bot config. Nothing essential to the running of the bot. All changes, I would think, have no different to the bot being deployed any way differently than normal.
> 
> My changes run fine locally but it all goes to whack on Heroku and due to the nature of Heroku it's hard to figure out exactly why.

For heroku you need to do dotnet publish command, when you do it in MSVC it does the dotnet build - already difference. That you replace only NadekoBot.Core.dll is already weird, why not compile the executable project and replace the whole thing. If you modifying the code, means that you need to use the guide below for that repo, where it's easy to make a mistake. Etc

**Comment by jtbry** [comment]
Okay thanks for the reply!.
