### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by Marxz-Kleanex** [ScarletKuro/NadekoBot#30]
I can't deploy app it says "There was an issue setting up your app environment.

Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify" how to fix this?

**Comment by ScarletKuro** [comment]
Answered here: https://github.com/ScarletKuro/NadekoBot-Heroku-Auto-Deploy/issues/6
Everything is correct, you have to enter credit card to be able to use the plugins.
