### ISSUE TITLE
idk what i do wrong

### ISSUE THREAD

**Issue by boozzeeboom** [ScarletKuro/NadekoBot#31]
Unhandled Exception: System.ArgumentException: No endpoints specified
Jul 14 16:17:20 lariska app[worker] info Parameter name: configuration 
Jul 14 16:17:20 lariska app[worker] info    at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 832 
Jul 14 16:17:20 lariska app[worker] info    at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 857 
Jul 14 16:17:20 lariska app[worker] info    at NadekoBot.Core.Services.ShardsCoordinator..ctor() in C:\Users\Kuro\NadekoBot\NadekoBot.Core\Services\ShardsCoordinator.cs:line 83 
Jul 14 16:17:20 lariska app[worker] info    at NadekoBot.Program.Main(String[] args) in C:\Users\Kuro\NadekoBot\src\NadekoBot\Program.cs:line 20 
Jul 14 16:17:20 lariska app[worker] info    at NadekoBot.Program.<Main>(String[] args) 
run.sh: line 7:    28 Aborted                 ../.heroku/dotnet/dotnet NadekoBot.dll

and if i do auto-deploy all worked correctly, but i cant clone it to make some changes at bot files, like images and else =( it will cloned empty folder

**Comment by boozzeeboom** [comment]
> Unhandled Exception: System.ArgumentException: No endpoints specified
> Jul 14 16:17:20 lariska app[worker] info Parameter name: configuration
> Jul 14 16:17:20 lariska app[worker] info at StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer(Object configuration) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 832
> Jul 14 16:17:20 lariska app[worker] info at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 857
> Jul 14 16:17:20 lariska app[worker] info at NadekoBot.Core.Services.ShardsCoordinator..ctor() in C:\Users\Kuro\NadekoBot\NadekoBot.Core\Services\ShardsCoordinator.cs:line 83
> Jul 14 16:17:20 lariska app[worker] info at NadekoBot.Program.Main(String[] args) in C:\Users\Kuro\NadekoBot\src\NadekoBot\Program.cs:line 20
> Jul 14 16:17:20 lariska app[worker] info at NadekoBot.Program.
> 
> (String[] args)

and if i do auto-deploy all worked correctly, but  i cant clone it to make some changes at bot files, like images and else =(

**Comment by ScarletKuro** [comment]
solved
