### ISSUE TITLE
How to host it in my computer(not heroku)

### ISSUE THREAD

**Issue by teorailin** [ScarletKuro/NadekoBot#32]
i want to host it in my linux computer, how can i do that?

**Comment by ScarletKuro** [comment]
Why are you asking here then? There is official discord nadeko server where you can ask this question and there is official nadeko website with the guides. Here is one of them to install it on your linux https://nadekobot.readthedocs.io/en/latest/guides/linux-guide/

**Comment by teorailin** [comment]
ok thx!
